"""Canonical policy and HTTP reason codes (M0 §7.3 and §10.4)."""

from __future__ import annotations

from enum import StrEnum


class HttpCode(StrEnum):
    OK = "OK"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    POLICY_REJECTED = "POLICY_REJECTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ReasonCode(StrEnum):
    """Engine reason_code values. HTTP maps business rejects to POLICY_REJECTED."""

    MAX_OUTBOUND_EXCEEDED = "MAX_OUTBOUND_EXCEEDED"
    DAILY_LIMIT_EXCEEDED = "DAILY_LIMIT_EXCEEDED"
    CAPITAL_AT_RISK_EXCEEDED = "CAPITAL_AT_RISK_EXCEEDED"
    PROHIBITED_TOKEN = "PROHIBITED_TOKEN"
    PROHIBITED_DESTINATION = "PROHIBITED_DESTINATION"
    UNKNOWN_CONTRACT = "UNKNOWN_CONTRACT"
    NO_JOB_PURPOSE = "NO_JOB_PURPOSE"
    BORROW_OR_LEVERAGE = "BORROW_OR_LEVERAGE"
    SWAP_OR_SPECULATE = "SWAP_OR_SPECULATE"
    POLICY_TAMPER = "POLICY_TAMPER"
    FROZEN = "FROZEN"
    SIGNER_DISABLED = "SIGNER_DISABLED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    UNSUPPORTED_WALLET_PHASE = "UNSUPPORTED_WALLET_PHASE"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    ASSET_MISMATCH = "ASSET_MISMATCH"
    AGENT_POLICY_MUTATION = "AGENT_POLICY_MUTATION"
    MARGIN_NOT_MET = "MARGIN_NOT_MET"
    OPEN_JOBS_EXCEEDED = "OPEN_JOBS_EXCEEDED"
