"""Incident kinds written by the supervisor. No automatic recovery."""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID


@dataclass(frozen=True)
class IncidentDraft:
    severity: str
    kind: str
    message: str
    correlation_id: UUID | None = None


WALLET_LEDGER_MISMATCH = "WALLET_LEDGER_MISMATCH"
POLICY_TAMPER = "POLICY_TAMPER"
FAKE_PAYMENT = "FAKE_PAYMENT"
AGENT_FROZEN = "AGENT_FROZEN"
SIGNER_DISABLED = "SIGNER_DISABLED"
LOOP_STOPPED = "LOOP_STOPPED"
UNEXPECTED_BALANCE = "UNEXPECTED_BALANCE"
DAILY_SPEND_WARN = "DAILY_SPEND_WARN"
DAILY_SPEND_CAP = "DAILY_SPEND_CAP"
CAPITAL_AT_RISK = "CAPITAL_AT_RISK"
FAILED_TXS = "FAILED_TXS"
POLICY_REJECTIONS = "POLICY_REJECTIONS"
UNUSUAL_DESTINATION = "UNUSUAL_DESTINATION"
COMPUTE_VELOCITY = "COMPUTE_VELOCITY"
JOB_FAILURE_RATE = "JOB_FAILURE_RATE"
CONTROL_UNHEALTHY = "CONTROL_UNHEALTHY"
UNREADABLE_STATE = "UNREADABLE_STATE"
